id = "csound"
name = "Csound Zed Support"
version = "1.2.1"
schema_version = 1
authors = ["Pasquale Mainolfi <mnlpql@gmail.com>"]
description = "tree-sitter-csound grammar"
repository = "https://github.com/PasqualeMainolfi/csound-zed"


[grammars.csound]
repository = "https://github.com/PasqualeMainolfi/tree-sitter-csound"
rev = "86fa072d6690c81f0076e3f042867719ad0a13ce"

[language_servers.csound-lsp]
name = "Csound"
languages = ["Csound"]
