id = "csound"
name = "Csound Zed Support"
version = "1.0.3"
schema_version = 1
authors = ["Pasquale Mainolfi <mnlpql@gmail.com>"]
description = "tree-sitter-csound grammar"
repository = "https://github.com/PasqualeMainolfi/csound-zed"


[grammars.csound]
repository = "https://github.com/PasqualeMainolfi/tree-sitter-csound"
rev = "c3c4f97133d7ae96c456102ed975468edd50842a"

[language_servers.csound-lsp]
name = "Csound"
languages = ["Csound"]
